<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="main" nsURI="http://www.example.org/main" nsPrefix="main">
  <eClassifiers xsi:type="ecore:EClass" name="Configuration" eSuperTypes="#//GeneralComponent #//GeneralConnector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//GeneralComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectors" upperBound="-1"
        eType="#//GeneralConnector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//ILink" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface" lowerBound="1"
        eType="#//InterfaceConfiguration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//GeneralComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="required" lowerBound="1"
        eType="#//InterfaceComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provided" lowerBound="1"
        eType="#//InterfaceComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prop" upperBound="-1" eType="#//IProperty"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraints" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connector" eSuperTypes="#//GeneralConnector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="glue" lowerBound="1" eType="#//Glue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TypeConnector"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IInterface" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceComponent" eSuperTypes="#//IInterface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" upperBound="-1"
        eType="#//Service" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
        eType="#//PortComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceConnector" eSuperTypes="#//IInterface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" upperBound="-1" eType="#//Role"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceConfiguration" eSuperTypes="#//IInterface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
        eType="#//PortConfiguration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ILink" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attachment" eSuperTypes="#//ILink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" lowerBound="1" eType="#//Role"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" lowerBound="1" eType="#//PortComponent"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Binding" eSuperTypes="#//ILink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="portComponent" lowerBound="1"
        eType="#//PortComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portConfiguration" lowerBound="1"
        eType="#//PortConfiguration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service"/>
  <eClassifiers xsi:type="ecore:EClass" name="Role"/>
  <eClassifiers xsi:type="ecore:EClass" name="Glue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="provided" lowerBound="1"
        eType="#//InterfaceConnector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="required" lowerBound="1"
        eType="#//InterfaceConnector" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IPort" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="PortConfiguration" eSuperTypes="#//IPort"/>
  <eClassifiers xsi:type="ecore:EClass" name="PortComponent" eSuperTypes="#//IPort"/>
  <eClassifiers xsi:type="ecore:EClass" name="GeneralComponent" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="GeneralConnector" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IProperty" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Functional" eSuperTypes="#//IProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="Nonfunctional" eSuperTypes="#//IProperty"/>
  <eClassifiers xsi:type="ecore:EDataType" name="TypeConnector" instanceTypeName="TypeConnector"/>
</ecore:EPackage>
