<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="">
  <eClassifiers xsi:type="ecore:EClass" name="Client" eSuperTypes="model/main.ecore#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="Server" eSuperTypes="model/main.ecore#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionManager" eSuperTypes="model/main.ecore#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServerConfig" eSuperTypes="model/main.ecore#//Configuration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="neweclass10" eType="#//NewEClass10"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityManager" eSuperTypes="model/main.ecore#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="Database" eSuperTypes="model/main.ecore#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClientConfig" eSuperTypes="model/main.ecore#//Configuration"/>
  <eClassifiers xsi:type="ecore:EClass" name="RPC" eSuperTypes="model/main.ecore#//Connector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gluerpc" eType="#//GlueRPC"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GlueRPC" eSuperTypes="model/main.ecore#//Glue"/>
  <eClassifiers xsi:type="ecore:EClass" name="NewEClass10"/>
</ecore:EPackage>
